DROP TABLE IF EXISTS users, locations, categories, events, requests;

CREATE TABLE IF NOT EXISTS users
(
    id    bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS locations
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lat FLOAT                                   NOT NULL,
    lon FLOAT                                   NOT NULL,
    CONSTRAINT pk_locations PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS categories
(
    id    bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT uq_category_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS events
(
    id                 bigint GENERATED BY DEFAULT AS IDENTITY             NOT NULL,
    annotation         VARCHAR(255)                                        NOT NULL,
    category_id        bigint REFERENCES categories (id) ON DELETE CASCADE NOT NULL,
    confirmedRequests  integer                                             NOT NULL,
    createdOn          TimeStamp WITHOUT TIME ZONE                         NOT NULL,
    description        VARCHAR(1024)                                       NOT NULL,
    eventDate          TimeStamp WITHOUT TIME ZONE                         NOT NULL,
    initiator_id       bigint REFERENCES users (id) ON DELETE CASCADE      NOT NULL,
    location_id        bigint REFERENCES locations (id) ON DELETE CASCADE  NOT NULL,
    paid               boolean                                             NOT NULL,
    participant_limit  integer                                             NOT NULL,
    published_on       TimeStamp WITHOUT TIME ZONE                         NOT NULL,
    request_moderation boolean                                             NOT NULL,
    title              VARCHAR(255)                                        NOT NULL,
    state              VARCHAR(255)                                        NOT NULL,
    views              integer                                             NOT NULL,
    CONSTRAINT pk_events PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS requests
(
    id        bigint GENERATED BY DEFAULT AS IDENTITY         NOT NULL,
    created   TimeStamp WITHOUT TIME ZONE                     NOT NULL,
    event_id  bigint REFERENCES events (id) ON DELETE CASCADE NOT NULL,
    requester bigint REFERENCES users (id) ON DELETE CASCADE  NOT NULL,
    status    VARCHAR(255)                                    NOT NULL,
    CONSTRAINT pk_requests PRIMARY KEY (id)
);


